# Generated by Django 6.0.7 on 2026-07-29 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0003_comment_likes_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='roleplay.comment'),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='character',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='sexuality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='theme_preference',
            field=models.CharField(default='dark_default', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(),
        ),
    ]
