# Generated by Django 6.0.7 on 2026-07-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0004_comment_parent_alter_character_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='roleplay.character'),
        ),
    ]
