# Generated by Django 6.0.7 on 2026-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0005_character_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='muted_characters',
            field=models.ManyToManyField(blank=True, related_name='muted_by', to='roleplay.character'),
        ),
    ]
