# Generated by Django 6.0.7 on 2026-07-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
