# Generated by Django 6.0.7 on 2026-08-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0008_alter_character_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_alpha_tester',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='show_alpha_badge',
            field=models.BooleanField(default=True),
        ),
    ]
