# Generated by Django 6.0.7 on 2026-08-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0009_character_is_alpha_tester_character_show_alpha_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fl_coins',
            field=models.IntegerField(default=150),
        ),
    ]
