# Generated by Django 6.0.7 on 2026-08-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0010_character_fl_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='active_effect',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='last_daily_chat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='last_daily_post',
            field=models.DateField(blank=True, null=True),
        ),
    ]
