# Generated by Django 6.0.7 on 2026-08-02 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0011_character_active_effect_character_last_daily_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('coin_reward', models.IntegerField(default=100)),
                ('target_count', models.IntegerField(default=1)),
                ('achievement_type', models.CharField(choices=[('posts', 'Quantidade de Posts'), ('messages', 'Mensagens Privadas'), ('followers', 'Seguidores Alcançados')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_on', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleplay.achievement')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_unlocked', to='roleplay.character')),
            ],
            options={
                'unique_together': {('character', 'achievement')},
            },
        ),
    ]
