# Generated by Django 6.0.7 on 2026-08-02 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0012_achievement_characterachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rules', models.TextField(blank=True, null=True)),
                ('niche', models.CharField(choices=[('rpg', 'RPG (Fantasia, Ação, etc)'), ('fake', 'Fake / Vida Real'), ('interagir', 'Interação / Slice of Life'), ('outro', 'Outro Nicho')], default='interagir', max_length=20)),
                ('privacy', models.CharField(choices=[('open', 'Aberto (Qualquer um entra)'), ('request', 'Somente com Solicitação')], default='open', max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='universe_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='universes_joined', to='roleplay.character')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_universes', to='roleplay.character')),
                ('pending_members', models.ManyToManyField(blank=True, related_name='universe_requests', to='roleplay.character')),
            ],
        ),
    ]
