# Generated by Django 6.0.7 on 2026-08-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0013_universe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniverseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='universe_chat/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleplay.character')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='roleplay.universe')),
            ],
        ),
    ]
