# Generated by Django 6.0.7 on 2026-08-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0014_universemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='max_characters',
            field=models.IntegerField(default=2),
        ),
    ]
