# Generated by Django 6.0.7 on 2026-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0015_player_is_premium_alter_player_max_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='font_style',
            field=models.CharField(blank=True, default='sans-serif', max_length=50, null=True),
        ),
    ]
