# Generated by Django 6.0.7 on 2026-08-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0017_postreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
