# Generated by Django 6.0.7 on 2026-08-06 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0019_saga'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='roleplay.saga'),
        ),
    ]
