# Generated by Django 6.0.7 on 2026-08-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0020_post_saga'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
