import os
from pathlib import Path

"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.7.
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0#-(*v%3x@zot2**40c9r!l9(mnxz&2v7lztef%f4vq!osq!=6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Liberado para o Ngrok e acesso externo
ALLOWED_HOSTS = ['*']

# ADICIONADO: Proteção CSRF liberada para os links do Ngrok e Localhost
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Nossas ferramentas:
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'roleplay', 
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # CORREÇÃO: O diretório de templates agora está no local certo
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Modelo de Usuário Customizado
AUTH_USER_MODEL = 'roleplay.Player'

# Libera nossa API para ser acessada por qualquer frontend localmente/ngrok
CORS_ALLOW_ALL_ORIGINS = True

# Configurações do Spotify API
SPOTIFY_CLIENT_ID = '9cdd52fccb8c4e3996eb5dc4fa0cb62f'
SPOTIFY_CLIENT_SECRET = 'f61d1743ebc647db84befa3fe1899e1f'

# Configuração de Arquivos de Mídia (Uploads de usuários/personagens)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Configuração do Django Rest Framework (DRF)
REST_FRAMEWORK = {
    # Desativa a autenticação por sessão (que causa o erro 403 de CSRF) e usa apenas Tokens
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # Permite que qualquer um tente fazer login (as outras rotas protegemos depois)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}